In [2]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [3]:
data = pd.DataFrame([("i love spending time with my friends and family", "positive"),
                     ("that was the best meal i've ever had in my life", "positive"),
                     ("i feel so grateful for everything i have in my life", "positive"),
                     ("i received a promotion at work and i couldn't be happier", "positive"),
                     ("watching a beautiful sunset always fills me with joy", "positive"),
                     ("my partner surprised me with a thoughtful gift and it made my day", "positive"),
                     ("i am so proud of my daughter for graduating with honors", "positive"),
                     ("listening to my favorite music always puts me in a good mood", "positive"),
                     ("i love the feeling of accomplishment after completing a challenging task", "positive"),
                     ("i am excited to go on vacation next week", "positive"),
                     ("i feel so overwhelmed with work and responsibilities", "negative"),
                     ("the traffic during my commute is always so frustrating", "negative"),
                     ("i received a parking ticket and it ruined my day", "negative"),
                     ("i got into an argument with my partner and we're not speaking", "negative"),
                     ("i have a headache and i feel terrible", "negative"),
                     ("i received a rejection letter for the job i really wanted", "negative"),
                     ("my car broke down and it's going to be expensive to fix", "negative"),
                     ("i'm feeling sad because i miss my friends who live far away", "negative"),
                     ("i'm frustrated because i can't seem to make progress on my project", "negative"),
                     ("i'm disappointed because my team lost the game", "negative")],
                     columns=['text', 'sentiment'] )

In [4]:
data

                                                 text sentiment
0     i love spending time with my friends and family  positive
1     that was the best meal i've ever had in my life  positive
2   i feel so grateful for everything i have in my...  positive
3   i received a promotion at work and i couldn't ...  positive
4   watching a beautiful sunset always fills me wi...  positive
5   my partner surprised me with a thoughtful gift...  positive
6   i am so proud of my daughter for graduating wi...  positive
7   listening to my favorite music always puts me ...  positive
8   i love the feeling of accomplishment after com...  positive
9            i am excited to go on vacation next week  positive
10  i feel so overwhelmed with work and responsibi...  negative
11  the traffic during my commute is always so fru...  negative
12   i received a parking ticket and it ruined my day  negative
13  i got into an argument with my partner and we'...  negative
14              i have a headache and i feel terrible  negative
15  i received a rejection letter for the job i re...  negative
16  my car broke down and it's going to be expensi...  negative
17  i'm feeling sad because i miss my friends who ...  negative
18  i'm frustrated because i can't seem to make pr...  negative
19     i'm disappointed because my team lost the game  negative

In [5]:
data = data.sample(frac=1).reset_index(drop=True)     #sample-->random sample

In [6]:
data

                                                 text sentiment
0   i'm frustrated because i can't seem to make pr...  negative
1   i'm feeling sad because i miss my friends who ...  negative
2            i am excited to go on vacation next week  positive
3   i love the feeling of accomplishment after com...  positive
4   the traffic during my commute is always so fru...  negative
5      i'm disappointed because my team lost the game  negative
6   watching a beautiful sunset always fills me wi...  positive
7   my car broke down and it's going to be expensi...  negative
8    i received a parking ticket and it ruined my day  negative
9   listening to my favorite music always puts me ...  positive
10  i feel so grateful for everything i have in my...  positive
11    that was the best meal i've ever had in my life  positive
12  i feel so overwhelmed with work and responsibi...  negative
13              i have a headache and i feel terrible  negative
14    i love spending time with my friends and family  positive
15  my partner surprised me with a thoughtful gift...  positive
16  i am so proud of my daughter for graduating wi...  positive
17  i got into an argument with my partner and we'...  negative
18  i received a rejection letter for the job i re...  negative
19  i received a promotion at work and i couldn't ...  positive

In [7]:
x = data['text']
y = data['sentiment']

In [8]:
countvec = CountVectorizer()

In [9]:
countvec_fit = countvec.fit_transform(x)

In [10]:
bag_of_words = pd.DataFrame(countvec_fit.toarray(), columns = countvec.get_feature_names_out()) 
bag_of_words

,accomplishment,after,always,am,an,and,argument,at,away,be,...,vacation,ve,wanted,was,watching,we,week,who,with,work
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
7,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
12,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
13,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
15,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
16,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
17,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,1,0,0,1,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
19,0,0,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1

In [11]:
x_train, x_test, y_train, y_test = train_test_split(bag_of_words, y, test_size=0.3, random_state=7)

In [12]:
lr = LogisticRegression(random_state=1).fit(x_train, y_train)
lr

LogisticRegression(random_state=1)

In [13]:
 y_pred_lr = lr.predict(x_test)

In [14]:
accuracy_score(y_pred_lr, y_test)

0.3333333333333333

In [15]:
print(classification_report(y_test, y_pred_lr) )

              precision    recall  f1-score   support

    negative       0.00      0.00      0.00         4
    positive       0.33      1.00      0.50         2

    accuracy                           0.33         6
   macro avg       0.17      0.50      0.25         6
weighted avg       0.11      0.33      0.17         6

C:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [17]:
from sklearn.naive_bayes import MultinomialNB

In [18]:
nb = MultinomialNB().fit(x_train, y_train)

In [19]:
y_pred_nb = nb.predict(x_test)

In [20]:
accuracy_score(y_pred_nb, y_test)

0.5

In [22]:
print(classification_report(y_test, y_pred_nb))

              precision    recall  f1-score   support

    negative       0.67      0.50      0.57         4
    positive       0.33      0.50      0.40         2

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.56      0.50      0.51         6

In [23]:
from sklearn.linear_model import SGDClassifier

In [24]:
svm = SGDClassifier().fit(x_train, y_train)

In [25]:
y_pred_svm = svm.predict(x_test)

In [26]:
accuracy_score(y_pred_svm, y_test)

0.3333333333333333